---
- name: Strategies
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: First task
      command: sleep 1
      changed_when: false

    - name: Second task
      command: sleep 5
      changed_when: false

    - name: Third task
      command: sleep 10
      changed_when: false
