---

- name: data collection 
  hosts: all
  gather_facts: false
  become: yes

  tasks:
    - name : gather OS family only
      setup:
        filter:
          - ansible_os_family
          - ansible_processor
          - ansible_memtotal_mb
          - ansible_hostname
          - ansible_default_ipv4


    - name: show Hostname
      debug:
        msg: "Hostname: {{ ansible_hostname }}"

    - name: Show OS family
      debug:
        msg: "The OS family is {{ ansible_os_family }} "

    - name: show IPv4
      debug: 
        msg: "IP information: {{ ansible_default_ipv4 }}"      
          
    - name: show Processor info
      debug:
        msg: "CPU: {{ ansible_processor[2] }}"

    - name: show total memory
      debug:
        msg: "Total memory = {{ ansible_memtotal_mb }}" 

